// Mapping from two-letter country codes to three-letter country codes

export const countries = [
  {
    code: 'AD',
    label: 'Andorra',
    phone: '+376',
    countryCode: 'AND',
  },
  {
    code: 'AE',
    label: 'United Arab Emirates',
    phone: '+971',
    countryCode: 'ARE',
  },
  {
    code: 'AF',
    label: 'Afghanistan',
    phone: '+93',
    countryCode: 'AFG',
  },
  {
    code: 'AG',
    label: 'Antigua and Barbuda',
    phone: '+1-268',
    countryCode: 'ATG',
  },
  {
    code: 'AI',
    label: 'Anguilla',
    phone: '+1-264',
    countryCode: 'AIA',
  },
  {
    code: 'AL',
    label: 'Albania',
    phone: '+355',
    countryCode: 'ALB',
  },
  {
    code: 'AM',
    label: 'Armenia',
    phone: '+374',
    countryCode: 'ARM',
  },
  {
    code: 'AO',
    label: 'Angola',
    phone: '+244',
    countryCode: 'AGO',
  },
  {
    code: 'AQ',
    label: 'Antarctica',
    phone: '+672',
    countryCode: 'ATA',
  },
  {
    code: 'AR',
    label: 'Argentina',
    phone: '+54',
    countryCode: 'ARG',
  },
  {
    code: 'AS',
    label: 'American Samoa',
    phone: '+1-684',
    countryCode: 'ASM',
  },
  {
    code: 'AT',
    label: 'Austria',
    phone: '+43',
    countryCode: 'AUT',
  },
  {
    code: 'AW',
    label: 'Aruba',
    phone: '+297',
    countryCode: 'ABW',
  },
  {
    code: 'AX',
    label: 'Alland Islands',
    phone: '+358',
    countryCode: 'ALA',
  },
  {
    code: 'AZ',
    label: 'Azerbaijan',
    phone: '+994',
    countryCode: 'AZE',
  },
  {
    code: 'BA',
    label: 'Bosnia and Herzegovina',
    phone: '+387',
    countryCode: 'BIH',
  },
  {
    code: 'BB',
    label: 'Barbados',
    phone: '+1-246',
    countryCode: 'BRB',
  },
  {
    code: 'BD',
    label: 'Bangladesh',
    phone: '+880',
    countryCode: 'BGD',
  },
  {
    code: 'BE',
    label: 'Belgium',
    phone: '+32',
    countryCode: 'BEL',
  },
  {
    code: 'BF',
    label: 'Burkina Faso',
    phone: '+226',
    countryCode: 'BFA',
  },
  {
    code: 'BG',
    label: 'Bulgaria',
    phone: '+359',
    countryCode: 'BGR',
  },
  {
    code: 'BH',
    label: 'Bahrain',
    phone: '+973',
    countryCode: 'BHR',
  },
  {
    code: 'BI',
    label: 'Burundi',
    phone: '+257',
    countryCode: 'BDI',
  },
  {
    code: 'BJ',
    label: 'Benin',
    phone: '+229',
    countryCode: 'BEN',
  },
  {
    code: 'BL',
    label: 'Saint Barthelemy',
    phone: '+590',
    countryCode: 'BLM',
  },
  {
    code: 'BM',
    label: 'Bermuda',
    phone: '+1-441',
    countryCode: 'BMU',
  },
  {
    code: 'BN',
    label: 'Brunei Darussalam',
    phone: '+673',
    countryCode: 'BRN',
  },
  {
    code: 'BO',
    label: 'Bolivia',
    phone: '+591',
    countryCode: 'BOL',
  },
  {
    code: 'BR',
    label: 'Brazil',
    phone: '+55',
    countryCode: 'BRA',
  },
  {
    code: 'BS',
    label: 'Bahamas',
    phone: '+1-242',
    countryCode: 'BHS',
  },
  {
    code: 'BT',
    label: 'Bhutan',
    phone: '+975',
    countryCode: 'BTN',
  },
  {
    code: 'BV',
    label: 'Bouvet Island',
    phone: '+47',
    countryCode: 'BVT',
  },
  {
    code: 'BW',
    label: 'Botswana',
    phone: '+267',
    countryCode: 'BWA',
  },
  {
    code: 'BY',
    label: 'Belarus',
    phone: '+375',
    countryCode: 'BLR',
  },
  {
    code: 'BZ',
    label: 'Belize',
    phone: '+501',
    countryCode: 'BLZ',
  },
  {
    code: 'CA',
    label: 'Canada',
    phone: '+1',
    suggested: true,
    countryCode: 'CAN',
  },
  {
    code: 'CC',
    label: 'Cocos (Keeling) Islands',
    phone: '+61',
    countryCode: 'CCK',
  },
  {
    code: 'CD',
    label: 'Congo, Democratic Republic of the',
    phone: '+243',
    countryCode: 'COD',
  },
  {
    code: 'CF',
    label: 'Central African Republic',
    phone: '+236',
    countryCode: 'CAF',
  },
  {
    code: 'CG',
    label: 'Congo, Republic of the',
    phone: '+242',
    countryCode: 'COG',
  },
  {
    code: 'CH',
    label: 'Switzerland',
    phone: '+41',
    countryCode: 'CHE',
  },
  {
    code: 'CI',
    label: "Cote d'Ivoire",
    phone: '+225',
    countryCode: 'CIV',
  },
  {
    code: 'CK',
    label: 'Cook Islands',
    phone: '+682',
    countryCode: 'COK',
  },
  {
    code: 'CL',
    label: 'Chile',
    phone: '+56',
    countryCode: 'CHL',
  },
  {
    code: 'CM',
    label: 'Cameroon',
    phone: '+237',
    countryCode: 'CMR',
  },
  {
    code: 'CN',
    label: 'China',
    phone: '+86',
    countryCode: 'CHN',
  },
  {
    code: 'CO',
    label: 'Colombia',
    phone: '+57',
    countryCode: 'COL',
  },
  {
    code: 'CR',
    label: 'Costa Rica',
    phone: '+506',
    countryCode: 'CRI',
  },
  {
    code: 'CU',
    label: 'Cuba',
    phone: '+53',
    countryCode: 'CUB',
  },
  {
    code: 'CV',
    label: 'Cape Verde',
    phone: '+238',
    countryCode: 'CPV',
  },
  {
    code: 'CW',
    label: 'Curacao',
    phone: '+599',
    countryCode: 'CUW',
  },
  {
    code: 'CX',
    label: 'Christmas Island',
    phone: '+61',
    countryCode: 'CXR',
  },
  {
    code: 'CY',
    label: 'Cyprus',
    phone: '+357',
    countryCode: 'CYP',
  },
  {
    code: 'CZ',
    label: 'Czech Republic',
    phone: '+420',
    countryCode: 'CZE',
  },
  {
    code: 'DE',
    label: 'Germany',
    phone: '+49',
    suggested: true,
    countryCode: 'DEU',
  },
  {
    code: 'DJ',
    label: 'Djibouti',
    phone: '+253',
    countryCode: 'DJI',
  },
  {
    code: 'DK',
    label: 'Denmark',
    phone: '+45',
    countryCode: 'DNK',
  },
  {
    code: 'DM',
    label: 'Dominica',
    phone: '+1-767',
    countryCode: 'DMA',
  },
  {
    code: 'DO',
    label: 'Dominican Republic',
    phone: '+1-809',
    countryCode: 'DOM',
  },
  {
    code: 'DZ',
    label: 'Algeria',
    phone: '+213',
    countryCode: 'DZA',
  },
  {
    code: 'EC',
    label: 'Ecuador',
    phone: '+593',
    countryCode: 'ECU',
  },
  {
    code: 'EE',
    label: 'Estonia',
    phone: '+372',
    countryCode: 'EST',
  },
  {
    code: 'EG',
    label: 'Egypt',
    phone: '+20',
    countryCode: 'EGY',
  },
  {
    code: 'EH',
    label: 'Western Sahara',
    phone: '+212',
    countryCode: 'ESH',
  },
  {
    code: 'ER',
    label: 'Eritrea',
    phone: '+291',
    countryCode: 'ERI',
  },
  {
    code: 'ES',
    label: 'Spain',
    phone: '+34',
    countryCode: 'ESP',
  },
  {
    code: 'ET',
    label: 'Ethiopia',
    phone: '+251',
    countryCode: 'ETH',
  },
  {
    code: 'FI',
    label: 'Finland',
    phone: '+358',
    countryCode: 'FIN',
  },
  {
    code: 'FJ',
    label: 'Fiji',
    phone: '+679',
    countryCode: 'FJI',
  },
  {
    code: 'FK',
    label: 'Falkland Islands (Malvinas)',
    phone: '+500',
    countryCode: 'FLK',
  },
  {
    code: 'FM',
    label: 'Micronesia, Federated States of',
    phone: '+691',
    countryCode: 'FSM',
  },
  {
    code: 'FO',
    label: 'Faroe Islands',
    phone: '+298',
    countryCode: 'FRO',
  },
  {
    code: 'FR',
    label: 'France',
    phone: '+33',
    suggested: true,
    countryCode: 'FRA',
  },
  {
    code: 'GA',
    label: 'Gabon',
    phone: '+241',
    countryCode: 'GAB',
  },
  {
    code: 'GB',
    label: 'United Kingdom',
    phone: '+44',
    countryCode: 'GBR',
  },
  {
    code: 'GD',
    label: 'Grenada',
    phone: '+1-473',
    countryCode: 'GRD',
  },
  {
    code: 'GE',
    label: 'Georgia',
    phone: '+995',
    countryCode: 'GEO',
  },
  {
    code: 'GF',
    label: 'French Guiana',
    phone: '+594',
    countryCode: 'GUF',
  },
  {
    code: 'GG',
    label: 'Guernsey',
    phone: '+44',
    countryCode: 'GGY',
  },
  {
    code: 'GH',
    label: 'Ghana',
    phone: '+233',
    countryCode: 'GHA',
  },
  {
    code: 'GI',
    label: 'Gibraltar',
    phone: '+350',
    countryCode: 'GIB',
  },
  {
    code: 'GL',
    label: 'Greenland',
    phone: '+299',
    countryCode: 'GRL',
  },
  {
    code: 'GM',
    label: 'Gambia',
    phone: '+220',
    countryCode: 'GMB',
  },
  {
    code: 'GN',
    label: 'Guinea',
    phone: '+224',
    countryCode: 'GIN',
  },
  {
    code: 'GP',
    label: 'Guadeloupe',
    phone: '+590',
    countryCode: 'GLP',
  },
  {
    code: 'GQ',
    label: 'Equatorial Guinea',
    phone: '+240',
    countryCode: 'GNQ',
  },
  {
    code: 'GR',
    label: 'Greece',
    phone: '+30',
    countryCode: 'GRC',
  },
  {
    code: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
    phone: '+500',
    countryCode: 'SGS',
  },
  {
    code: 'GT',
    label: 'Guatemala',
    phone: '+502',
    countryCode: 'GTM',
  },
  {
    code: 'GU',
    label: 'Guam',
    phone: '+1-671',
    countryCode: 'GUM',
  },
  {
    code: 'GW',
    label: 'Guinea-Bissau',
    phone: '+245',
    countryCode: 'GNB',
  },
  {
    code: 'GY',
    label: 'Guyana',
    phone: '+592',
    countryCode: 'GUY',
  },
  {
    code: 'HK',
    label: 'Hong Kong',
    phone: '+852',
    countryCode: 'HKG',
  },
  {
    code: 'HM',
    label: 'Heard Island and McDonald Islands',
    phone: '+672',
    countryCode: 'HMD',
  },
  {
    code: 'HN',
    label: 'Honduras',
    phone: '+504',
    countryCode: 'HND',
  },
  {
    code: 'HR',
    label: 'Croatia',
    phone: '+385',
    countryCode: 'HRV',
  },
  {
    code: 'HT',
    label: 'Haiti',
    phone: '+509',
    countryCode: 'HTI',
  },
  {
    code: 'HU',
    label: 'Hungary',
    phone: '+36',
    countryCode: 'HUN',
  },
  {
    code: 'ID',
    label: 'Indonesia',
    phone: '+62',
    countryCode: 'IDN',
  },
  {
    code: 'IE',
    label: 'Ireland',
    phone: '+353',
    countryCode: 'IRL',
  },
  {
    code: 'IL',
    label: 'Israel',
    phone: '+972',
    countryCode: 'ISR',
  },
  {
    code: 'IM',
    label: 'Isle of Man',
    phone: '+44',
    countryCode: 'IMN',
  },
  {
    code: 'IN',
    label: 'India',
    phone: '+91',
    countryCode: 'IND',
  },
  {
    code: 'IO',
    label: 'British Indian Ocean Territory',
    phone: '+246',
    countryCode: 'IOT',
  },
  {
    code: 'IQ',
    label: 'Iraq',
    phone: '+964',
    countryCode: 'IRQ',
  },
  {
    code: 'IR',
    label: 'Iran, Islamic Republic of',
    phone: '+98',
    countryCode: 'IRN',
  },
  {
    code: 'IS',
    label: 'Iceland',
    phone: '+354',
    countryCode: 'ISL',
  },
  {
    code: 'IT',
    label: 'Italy',
    phone: '+39',
    countryCode: 'ITA',
  },
  {
    code: 'JE',
    label: 'Jersey',
    phone: '+44',
    countryCode: 'JEY',
  },
  {
    code: 'JM',
    label: 'Jamaica',
    phone: '+1-876',
    countryCode: 'JAM',
  },
  {
    code: 'JO',
    label: 'Jordan',
    phone: '+962',
    countryCode: 'JOR',
  },
  {
    code: 'JP',
    label: 'Japan',
    phone: '+81',
    suggested: true,
    countryCode: 'JPN',
  },
  {
    code: 'KE',
    label: 'Kenya',
    phone: '+254',
    countryCode: 'KEN',
  },
  {
    code: 'KG',
    label: 'Kyrgyzstan',
    phone: '+996',
    countryCode: 'KGZ',
  },
  {
    code: 'KH',
    label: 'Cambodia',
    phone: '+855',
    countryCode: 'KHM',
  },
  {
    code: 'KI',
    label: 'Kiribati',
    phone: '+686',
    countryCode: 'KIR',
  },
  {
    code: 'KM',
    label: 'Comoros',
    phone: '+269',
    countryCode: 'COM',
  },
  {
    code: 'KN',
    label: 'Saint Kitts and Nevis',
    phone: '+1-869',
    countryCode: 'KNA',
  },
  {
    code: 'KP',
    label: "Korea, Democratic People's Republic of",
    phone: '+850',
    countryCode: 'PRK',
  },
  {
    code: 'KR',
    label: 'Korea, Republic of',
    phone: '+82',
    countryCode: 'KOR',
  },
  {
    code: 'KW',
    label: 'Kuwait',
    phone: '+965',
    countryCode: 'KWT',
  },
  {
    code: 'KY',
    label: 'Cayman Islands',
    phone: '+1-345',
    countryCode: 'CYM',
  },
  {
    code: 'KZ',
    label: 'Kazakhstan',
    phone: '+7',
    countryCode: 'KAZ',
  },
  {
    code: 'LA',
    label: "Lao People's Democratic Republic",
    phone: '+856',
    countryCode: 'LAO',
  },
  {
    code: 'LB',
    label: 'Lebanon',
    phone: '+961',
    countryCode: 'LBN',
  },
  {
    code: 'LC',
    label: 'Saint Lucia',
    phone: '+1-758',
    countryCode: 'LCA',
  },
  {
    code: 'LI',
    label: 'Liechtenstein',
    phone: '+423',
    countryCode: 'LIE',
  },
  {
    code: 'LK',
    label: 'Sri Lanka',
    phone: '+94',
    countryCode: 'LKA',
  },
  {
    code: 'LR',
    label: 'Liberia',
    phone: '+231',
    countryCode: 'LBR',
  },
  {
    code: 'LS',
    label: 'Lesotho',
    phone: '+266',
    countryCode: 'LSO',
  },
  {
    code: 'LT',
    label: 'Lithuania',
    phone: '+370',
    countryCode: 'LTU',
  },
  {
    code: 'LU',
    label: 'Luxembourg',
    phone: '+352',
    countryCode: 'LUX',
  },
  {
    code: 'LV',
    label: 'Latvia',
    phone: '+371',
    countryCode: 'LVA',
  },
  {
    code: 'LY',
    label: 'Libya',
    phone: '+218',
    countryCode: 'LBY',
  },
  {
    code: 'MA',
    label: 'Morocco',
    phone: '+212',
    countryCode: 'MAR',
  },
  {
    code: 'MC',
    label: 'Monaco',
    phone: '+377',
    countryCode: 'MCO',
  },
  {
    code: 'MD',
    label: 'Moldova, Republic of',
    phone: '+373',
    countryCode: 'MDA',
  },
  {
    code: 'ME',
    label: 'Montenegro',
    phone: '+382',
    countryCode: 'MNE',
  },
  {
    code: 'MF',
    label: 'Saint Martin (French part)',
    phone: '+590',
    countryCode: 'MAF',
  },
  {
    code: 'MG',
    label: 'Madagascar',
    phone: '+261',
    countryCode: 'MDG',
  },
  {
    code: 'MH',
    label: 'Marshall Islands',
    phone: '+692',
    countryCode: 'MHL',
  },
  {
    code: 'MK',
    label: 'Macedonia, the Former Yugoslav Republic of',
    phone: '+389',
    countryCode: 'MKD',
  },
  {
    code: 'ML',
    label: 'Mali',
    phone: '+223',
    countryCode: 'MLI',
  },
  {
    code: 'MM',
    label: 'Myanmar',
    phone: '+95',
    countryCode: 'MMR',
  },
  {
    code: 'MN',
    label: 'Mongolia',
    phone: '+976',
    countryCode: 'MNG',
  },
  {
    code: 'MO',
    label: 'Macao',
    phone: '+853',
    countryCode: 'MAC',
  },
  {
    code: 'MP',
    label: 'Northern Mariana Islands',
    phone: '+1-670',
    countryCode: 'MNP',
  },
  {
    code: 'MQ',
    label: 'Martinique',
    phone: '+596',
    countryCode: 'MTQ',
  },
  {
    code: 'MR',
    label: 'Mauritania',
    phone: '+222',
    countryCode: 'MRT',
  },
  {
    code: 'MS',
    label: 'Montserrat',
    phone: '+1-664',
    countryCode: 'MSR',
  },
  {
    code: 'MT',
    label: 'Malta',
    phone: '+356',
    countryCode: 'MLT',
  },
  {
    code: 'MU',
    label: 'Mauritius',
    phone: '+230',
    countryCode: 'MUS',
  },
  {
    code: 'MV',
    label: 'Maldives',
    phone: '+960',
    countryCode: 'MDV',
  },
  {
    code: 'MW',
    label: 'Malawi',
    phone: '+265',
    countryCode: 'MWI',
  },
  {
    code: 'MX',
    label: 'Mexico',
    phone: '+52',
    countryCode: 'MEX',
  },
  {
    code: 'MY',
    label: 'Malaysia',
    phone: '+60',
    countryCode: 'MYS',
  },
  {
    code: 'MZ',
    label: 'Mozambique',
    phone: '+258',
    countryCode: 'MOZ',
  },
  {
    code: 'NA',
    label: 'Namibia',
    phone: '+264',
    countryCode: 'NAM',
  },
  {
    code: 'NC',
    label: 'New Caledonia',
    phone: '+687',
    countryCode: 'NCL',
  },
  {
    code: 'NE',
    label: 'Niger',
    phone: '+227',
    countryCode: 'NER',
  },
  {
    code: 'NF',
    label: 'Norfolk Island',
    phone: '+672',
    countryCode: 'NFK',
  },
  {
    code: 'NG',
    label: 'Nigeria',
    phone: '+234',
    countryCode: 'NGA',
  },
  {
    code: 'NI',
    label: 'Nicaragua',
    phone: '+505',
    countryCode: 'NIC',
  },
  {
    code: 'NL',
    label: 'Netherlands',
    phone: '+31',
    countryCode: 'NLD',
  },
  {
    code: 'NO',
    label: 'Norway',
    phone: '+47',
    countryCode: 'NOR',
  },
  {
    code: 'NP',
    label: 'Nepal',
    phone: '+977',
    countryCode: 'NPL',
  },
  {
    code: 'NR',
    label: 'Nauru',
    phone: '+674',
    countryCode: 'NRU',
  },
  {
    code: 'NU',
    label: 'Niue',
    phone: '+683',
    countryCode: 'NIU',
  },
  {
    code: 'NZ',
    label: 'New Zealand',
    phone: '+64',
    countryCode: 'NZL',
  },
  {
    code: 'OM',
    label: 'Oman',
    phone: '+968',
    countryCode: 'OMN',
  },
  {
    code: 'PA',
    label: 'Panama',
    phone: '+507',
    countryCode: 'PAN',
  },
  {
    code: 'PE',
    label: 'Peru',
    phone: '+51',
    countryCode: 'PER',
  },
  {
    code: 'PF',
    label: 'French Polynesia',
    phone: '+689',
    countryCode: 'PYF',
  },
  {
    code: 'PG',
    label: 'Papua New Guinea',
    phone: '+675',
    countryCode: 'PNG',
  },
  {
    code: 'PH',
    label: 'Philippines',
    phone: '+63',
    countryCode: 'PHL',
  },
  {
    code: 'PK',
    label: 'Pakistan',
    phone: '+92',
    countryCode: 'PAK',
  },
  {
    code: 'PL',
    label: 'Poland',
    phone: '+48',
    countryCode: 'POL',
  },
  {
    code: 'PM',
    label: 'Saint Pierre and Miquelon',
    phone: '+508',
    countryCode: 'SPM',
  },
  {
    code: 'PN',
    label: 'Pitcairn',
    phone: '+870',
    countryCode: 'PCN',
  },
  {
    code: 'PR',
    label: 'Puerto Rico',
    phone: '+1',
    countryCode: 'PRI',
  },
  {
    code: 'PS',
    label: 'Palestine, State of',
    phone: '+970',
    countryCode: 'PSE',
  },
  {
    code: 'PT',
    label: 'Portugal',
    phone: '+351',
    countryCode: 'PRT',
  },
  {
    code: 'PW',
    label: 'Palau',
    phone: '+680',
    countryCode: 'PLW',
  },
  {
    code: 'PY',
    label: 'Paraguay',
    phone: '+595',
    countryCode: 'PRY',
  },
  {
    code: 'QA',
    label: 'Qatar',
    phone: '+974',
    countryCode: 'QAT',
  },
  {
    code: 'RE',
    label: 'Reunion',
    phone: '+262',
    countryCode: 'REU',
  },
  {
    code: 'RO',
    label: 'Romania',
    phone: '+40',
    countryCode: 'ROU',
  },
  {
    code: 'RS',
    label: 'Serbia',
    phone: '+381',
    countryCode: 'SRB',
  },
  {
    code: 'RU',
    label: 'Russian Federation',
    phone: '+7',
    countryCode: 'RUS',
  },
  {
    code: 'RW',
    label: 'Rwanda',
    phone: '+250',
    countryCode: 'RWA',
  },
  {
    code: 'SA',
    label: 'Saudi Arabia',
    phone: '+966',
    countryCode: 'SAU',
  },
  {
    code: 'SB',
    label: 'Solomon Islands',
    phone: '+677',
    countryCode: 'SLB',
  },
  {
    code: 'SC',
    label: 'Seychelles',
    phone: '+248',
    countryCode: 'SYC',
  },
  {
    code: 'SD',
    label: 'Sudan',
    phone: '+249',
    countryCode: 'SDN',
  },
  {
    code: 'SE',
    label: 'Sweden',
    phone: '+46',
    countryCode: 'SWE',
  },
  {
    code: 'SG',
    label: 'Singapore',
    phone: '+65',
    countryCode: 'SGP',
  },
  {
    code: 'SH',
    label: 'Saint Helena',
    phone: '+290',
    countryCode: 'SHN',
  },
  {
    code: 'SI',
    label: 'Slovenia',
    phone: '+386',
    countryCode: 'SVN',
  },
  {
    code: 'SJ',
    label: 'Svalbard and Jan Mayen',
    phone: '+47',
    countryCode: 'SJM',
  },
  {
    code: 'SK',
    label: 'Slovakia',
    phone: '+421',
    countryCode: 'SVK',
  },
  {
    code: 'SL',
    label: 'Sierra Leone',
    phone: '+232',
    countryCode: 'SLE',
  },
  {
    code: 'SM',
    label: 'San Marino',
    phone: '+378',
    countryCode: 'SMR',
  },
  {
    code: 'SN',
    label: 'Senegal',
    phone: '+221',
    countryCode: 'SEN',
  },
  {
    code: 'SO',
    label: 'Somalia',
    phone: '+252',
    countryCode: 'SOM',
  },
  {
    code: 'SR',
    label: 'Suriname',
    phone: '+597',
    countryCode: 'SUR',
  },
  {
    code: 'SS',
    label: 'South Sudan',
    phone: '+211',
    countryCode: 'SSD',
  },
  {
    code: 'ST',
    label: 'Sao Tome and Principe',
    phone: '+239',
    countryCode: 'STP',
  },
  {
    code: 'SV',
    label: 'El Salvador',
    phone: '+503',
    countryCode: 'SLV',
  },
  {
    code: 'SX',
    label: 'Sint Maarten (Dutch part)',
    phone: '+1-721',
    countryCode: 'SXM',
  },
  {
    code: 'SY',
    label: 'Syrian Arab Republic',
    phone: '+963',
    countryCode: 'SYR',
  },
  {
    code: 'SZ',
    label: 'Swaziland',
    phone: '+268',
    countryCode: 'SWZ',
  },
  {
    code: 'TC',
    label: 'Turks and Caicos Islands',
    phone: '+1-649',
    countryCode: 'TCA',
  },
  {
    code: 'TD',
    label: 'Chad',
    phone: '+235',
    countryCode: 'TCD',
  },
  {
    code: 'TF',
    label: 'French Southern Territories',
    phone: '+262',
    countryCode: 'ATF',
  },
  {
    code: 'TG',
    label: 'Togo',
    phone: '+228',
    countryCode: 'TGO',
  },
  {
    code: 'TH',
    label: 'Thailand',
    phone: '+66',
    countryCode: 'THA',
  },
  {
    code: 'TJ',
    label: 'Tajikistan',
    phone: '+992',
    countryCode: 'TJK',
  },
  {
    code: 'TK',
    label: 'Tokelau',
    phone: '+690',
    countryCode: 'TKL',
  },
  {
    code: 'TL',
    label: 'Timor-Leste',
    phone: '+670',
    countryCode: 'TLS',
  },
  {
    code: 'TM',
    label: 'Turkmenistan',
    phone: '+993',
    countryCode: 'TKM',
  },
  {
    code: 'TN',
    label: 'Tunisia',
    phone: '+216',
    countryCode: 'TUN',
  },
  {
    code: 'TO',
    label: 'Tonga',
    phone: '+676',
    countryCode: 'TON',
  },
  {
    code: 'TR',
    label: 'Turkey',
    phone: '+90',
    countryCode: 'TUR',
  },
  {
    code: 'TT',
    label: 'Trinidad and Tobago',
    phone: '+1-868',
    countryCode: 'TTO',
  },
  {
    code: 'TV',
    label: 'Tuvalu',
    phone: '+688',
    countryCode: 'TUV',
  },
  {
    code: 'TW',
    label: 'Taiwan',
    phone: '+886',
    countryCode: 'TWN',
  },
  {
    code: 'TZ',
    label: 'United Republic of Tanzania',
    phone: '+255',
    countryCode: 'TZA',
  },
  {
    code: 'UA',
    label: 'Ukraine',
    phone: '+380',
    countryCode: 'UKR',
  },
  {
    code: 'UG',
    label: 'Uganda',
    phone: '+256',
    countryCode: 'UGA',
  },
  {
    code: 'US',
    label: 'United States',
    phone: '+1',
    suggested: true,
    countryCode: 'USA',
  },
  {
    code: 'UY',
    label: 'Uruguay',
    phone: '+598',
    countryCode: 'URY',
  },
  {
    code: 'UZ',
    label: 'Uzbekistan',
    phone: '+998',
    countryCode: 'UZB',
  },
  {
    code: 'VA',
    label: 'Holy See (Vatican City State)',
    phone: '+379',
    countryCode: 'VAT',
  },
  {
    code: 'VC',
    label: 'Saint Vincent and the Grenadines',
    phone: '+1-784',
    countryCode: 'VCT',
  },
  {
    code: 'VE',
    label: 'Venezuela',
    phone: '+58',
    countryCode: 'VEN',
  },
  {
    code: 'VG',
    label: 'British Virgin Islands',
    phone: '+1-284',
    countryCode: 'VGB',
  },
  {
    code: 'VI',
    label: 'US Virgin Islands',
    phone: '+1-340',
    countryCode: 'VIR',
  },
  {
    code: 'VN',
    label: 'Vietnam',
    phone: '+84',
    countryCode: 'VNM',
  },
  {
    code: 'VU',
    label: 'Vanuatu',
    phone: '+678',
    countryCode: 'VUT',
  },
  {
    code: 'WF',
    label: 'Wallis and Futuna',
    phone: '+681',
    countryCode: 'WLF',
  },
  {
    code: 'WS',
    label: 'Samoa',
    phone: '+685',
    countryCode: 'WSM',
  },
  {
    code: 'XK',
    label: 'Kosovo',
    phone: '+383',
    countryCode: 'XKX',
  },
  {
    code: 'YE',
    label: 'Yemen',
    phone: '+967',
    countryCode: 'YEM',
  },
  {
    code: 'YT',
    label: 'Mayotte',
    phone: '+262',
    countryCode: 'MYT',
  },
  {
    code: 'ZA',
    label: 'South Africa',
    phone: '+27',
    countryCode: 'ZAF',
  },
  {
    code: 'ZM',
    label: 'Zambia',
    phone: '+260',
    countryCode: 'ZMB',
  },
  {
    code: 'ZW',
    label: 'Zimbabwe',
    phone: '+263',
    countryCode: 'ZWE',
  },
];

export const SUPPORTED_COUNTRIES = [
  {
    code: 'AE',
    label: 'United Arab Emirates',
    phone: '+971',
    countryCode: 'ARE',
  },
  {
    code: 'AG',
    label: 'Antigua and Barbuda',
    phone: '+1-268',
    countryCode: 'ATG',
  },
  {
    code: 'AI',
    label: 'Anguilla',
    phone: '+1-264',
    countryCode: 'AIA',
  },
  {
    code: 'AL',
    label: 'Albania',
    phone: '+355',
    countryCode: 'ALB',
  },
  {
    code: 'AM',
    label: 'Armenia',
    phone: '+374',
    countryCode: 'ARM',
  },
  {
    code: 'AO',
    label: 'Angola',
    phone: '+244',
    countryCode: 'AGO',
  },
  {
    code: 'AQ',
    label: 'Antarctica',
    phone: '+672',
    countryCode: 'ATA',
  },
  {
    code: 'AR',
    label: 'Argentina',
    phone: '+54',
    countryCode: 'ARG',
  },
  {
    code: 'AS',
    label: 'American Samoa',
    phone: '+1-684',
    countryCode: 'ASM',
  },
  {
    code: 'AT',
    label: 'Austria',
    phone: '+43',
    countryCode: 'AUT',
  },
  {
    code: 'AU',
    label: 'Australia',
    phone: '+61',
    suggested: true,
    countryCode: 'AUS',
  },
  {
    code: 'AW',
    label: 'Aruba',
    phone: '+297',
    countryCode: 'ABW',
  },
  {
    code: 'AX',
    label: 'Alland Islands',
    phone: '+358',
    countryCode: 'ALA',
  },
  {
    code: 'AZ',
    label: 'Azerbaijan',
    phone: '+994',
    countryCode: 'AZE',
  },
  {
    code: 'BA',
    label: 'Bosnia and Herzegovina',
    phone: '+387',
    countryCode: 'BIH',
  },
  {
    code: 'BB',
    label: 'Barbados',
    phone: '+1-246',
    countryCode: 'BRB',
  },
  {
    code: 'BD',
    label: 'Bangladesh',
    phone: '+880',
    countryCode: 'BGD',
  },
  {
    code: 'BE',
    label: 'Belgium',
    phone: '+32',
    countryCode: 'BEL',
  },
  {
    code: 'BF',
    label: 'Burkina Faso',
    phone: '+226',
    countryCode: 'BFA',
  },
  {
    code: 'BG',
    label: 'Bulgaria',
    phone: '+359',
    countryCode: 'BGR',
  },
  {
    code: 'BH',
    label: 'Bahrain',
    phone: '+973',
    countryCode: 'BHR',
  },
  {
    code: 'BJ',
    label: 'Benin',
    phone: '+229',
    countryCode: 'BEN',
  },
  {
    code: 'BL',
    label: 'Saint Barthelemy',
    phone: '+590',
    countryCode: 'BLM',
  },
  {
    code: 'BM',
    label: 'Bermuda',
    phone: '+1-441',
    countryCode: 'BMU',
  },
  {
    code: 'BN',
    label: 'Brunei Darussalam',
    phone: '+673',
    countryCode: 'BRN',
  },
  {
    code: 'BO',
    label: 'Bolivia',
    phone: '+591',
    countryCode: 'BOL',
  },
  {
    code: 'BR',
    label: 'Brazil',
    phone: '+55',
    countryCode: 'BRA',
  },
  {
    code: 'BS',
    label: 'Bahamas',
    phone: '+1-242',
    countryCode: 'BHS',
  },
  {
    code: 'BT',
    label: 'Bhutan',
    phone: '+975',
    countryCode: 'BTN',
  },
  {
    code: 'BV',
    label: 'Bouvet Island',
    phone: '+47',
    countryCode: 'BVT',
  },
  {
    code: 'BW',
    label: 'Botswana',
    phone: '+267',
    countryCode: 'BWA',
  },
  {
    code: 'BZ',
    label: 'Belize',
    phone: '+501',
    countryCode: 'BLZ',
  },
  {
    code: 'CA',
    label: 'Canada',
    phone: '+1',
    suggested: true,
    countryCode: 'CAN',
  },
  {
    code: 'CC',
    label: 'Cocos (Keeling) Islands',
    phone: '+61',
    countryCode: 'CCK',
  },
  {
    code: 'CG',
    label: 'Congo, Republic of the',
    phone: '+242',
    countryCode: 'COG',
  },
  {
    code: 'CH',
    label: 'Switzerland',
    phone: '+41',
    countryCode: 'CHE',
  },
  {
    code: 'CI',
    label: "Cote d'Ivoire",
    phone: '+225',
    countryCode: 'CIV',
  },
  {
    code: 'CK',
    label: 'Cook Islands',
    phone: '+682',
    countryCode: 'COK',
  },
  {
    code: 'CL',
    label: 'Chile',
    phone: '+56',
    countryCode: 'CHL',
  },
  {
    code: 'CM',
    label: 'Cameroon',
    phone: '+237',
    countryCode: 'CMR',
  },
  {
    code: 'CO',
    label: 'Colombia',
    phone: '+57',
    countryCode: 'COL',
  },
  {
    code: 'CR',
    label: 'Costa Rica',
    phone: '+506',
    countryCode: 'CRI',
  },
  {
    code: 'CV',
    label: 'Cape Verde',
    phone: '+238',
    countryCode: 'CPV',
  },
  {
    code: 'CW',
    label: 'Curacao',
    phone: '+599',
    countryCode: 'CUW',
  },
  {
    code: 'CX',
    label: 'Christmas Island',
    phone: '+61',
    countryCode: 'CXR',
  },
  {
    code: 'CY',
    label: 'Cyprus',
    phone: '+357',
    countryCode: 'CYP',
  },
  {
    code: 'CZ',
    label: 'Czech Republic',
    phone: '+420',
    countryCode: 'CZE',
  },
  {
    code: 'DE',
    label: 'Germany',
    phone: '+49',
    suggested: true,
    countryCode: 'DEU',
  },
  {
    code: 'DJ',
    label: 'Djibouti',
    phone: '+253',
    countryCode: 'DJI',
  },
  {
    code: 'DK',
    label: 'Denmark',
    phone: '+45',
    countryCode: 'DNK',
  },
  {
    code: 'DM',
    label: 'Dominica',
    phone: '+1-767',
    countryCode: 'DMA',
  },
  {
    code: 'DO',
    label: 'Dominican Republic',
    phone: '+1-809',
    countryCode: 'DOM',
  },
  {
    code: 'DZ',
    label: 'Algeria',
    phone: '+213',
    countryCode: 'DZA',
  },
  {
    code: 'EC',
    label: 'Ecuador',
    phone: '+593',
    countryCode: 'ECU',
  },
  {
    code: 'EE',
    label: 'Estonia',
    phone: '+372',
    countryCode: 'EST',
  },
  {
    code: 'EG',
    label: 'Egypt',
    phone: '+20',
    countryCode: 'EGY',
  },
  {
    code: 'EH',
    label: 'Western Sahara',
    phone: '+212',
    countryCode: 'ESH',
  },
  {
    code: 'ES',
    label: 'Spain',
    phone: '+34',
    countryCode: 'ESP',
  },
  {
    code: 'ET',
    label: 'Ethiopia',
    phone: '+251',
    countryCode: 'ETH',
  },
  {
    code: 'FI',
    label: 'Finland',
    phone: '+358',
    countryCode: 'FIN',
  },
  {
    code: 'FJ',
    label: 'Fiji',
    phone: '+679',
    countryCode: 'FJI',
  },
  {
    code: 'FK',
    label: 'Falkland Islands (Malvinas)',
    phone: '+500',
    countryCode: 'FLK',
  },
  {
    code: 'FM',
    label: 'Micronesia, Federated States of',
    phone: '+691',
    countryCode: 'FSM',
  },
  {
    code: 'FO',
    label: 'Faroe Islands',
    phone: '+298',
    countryCode: 'FRO',
  },
  {
    code: 'FR',
    label: 'France',
    phone: '+33',
    suggested: true,
    countryCode: 'FRA',
  },
  {
    code: 'GA',
    label: 'Gabon',
    phone: '+241',
    countryCode: 'GAB',
  },
  {
    code: 'GB',
    label: 'United Kingdom',
    phone: '+44',
    countryCode: 'GBR',
  },
  {
    code: 'GD',
    label: 'Grenada',
    phone: '+1-473',
    countryCode: 'GRD',
  },
  {
    code: 'GE',
    label: 'Georgia',
    phone: '+995',
    countryCode: 'GEO',
  },
  {
    code: 'GF',
    label: 'French Guiana',
    phone: '+594',
    countryCode: 'GUF',
  },
  {
    code: 'GG',
    label: 'Guernsey',
    phone: '+44',
    countryCode: 'GGY',
  },
  {
    code: 'GH',
    label: 'Ghana',
    phone: '+233',
    countryCode: 'GHA',
  },
  {
    code: 'GI',
    label: 'Gibraltar',
    phone: '+350',
    countryCode: 'GIB',
  },
  {
    code: 'GL',
    label: 'Greenland',
    phone: '+299',
    countryCode: 'GRL',
  },
  {
    code: 'GM',
    label: 'Gambia',
    phone: '+220',
    countryCode: 'GMB',
  },
  {
    code: 'GP',
    label: 'Guadeloupe',
    phone: '+590',
    countryCode: 'GLP',
  },
  {
    code: 'GQ',
    label: 'Equatorial Guinea',
    phone: '+240',
    countryCode: 'GNQ',
  },
  {
    code: 'GR',
    label: 'Greece',
    phone: '+30',
    countryCode: 'GRC',
  },
  {
    code: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
    phone: '+500',
    countryCode: 'SGS',
  },
  {
    code: 'GT',
    label: 'Guatemala',
    phone: '+502',
    countryCode: 'GTM',
  },
  {
    code: 'GU',
    label: 'Guam',
    phone: '+1-671',
    countryCode: 'GUM',
  },
  {
    code: 'GW',
    label: 'Guinea-Bissau',
    phone: '+245',
    countryCode: 'GNB',
  },
  {
    code: 'GY',
    label: 'Guyana',
    phone: '+592',
    countryCode: 'GUY',
  },
  {
    code: 'HK',
    label: 'Hong Kong',
    phone: '+852',
    countryCode: 'HKG',
  },
  {
    code: 'HM',
    label: 'Heard Island and McDonald Islands',
    phone: '+672',
    countryCode: 'HMD',
  },
  {
    code: 'HN',
    label: 'Honduras',
    phone: '+504',
    countryCode: 'HND',
  },
  {
    code: 'HR',
    label: 'Croatia',
    phone: '+385',
    countryCode: 'HRV',
  },
  {
    code: 'HU',
    label: 'Hungary',
    phone: '+36',
    countryCode: 'HUN',
  },
  {
    code: 'ID',
    label: 'Indonesia',
    phone: '+62',
    countryCode: 'IDN',
  },
  {
    code: 'IE',
    label: 'Ireland',
    phone: '+353',
    countryCode: 'IRL',
  },
  {
    code: 'IL',
    label: 'Israel',
    phone: '+972',
    countryCode: 'ISR',
  },
  {
    code: 'IM',
    label: 'Isle of Man',
    phone: '+44',
    countryCode: 'IMN',
  },
  {
    code: 'IN',
    label: 'India',
    phone: '+91',
    countryCode: 'IND',
  },
  {
    code: 'IO',
    label: 'British Indian Ocean Territory',
    phone: '+246',
    countryCode: 'IOT',
  },
  {
    code: 'IS',
    label: 'Iceland',
    phone: '+354',
    countryCode: 'ISL',
  },
  {
    code: 'IT',
    label: 'Italy',
    phone: '+39',
    countryCode: 'ITA',
  },
  {
    code: 'JE',
    label: 'Jersey',
    phone: '+44',
    countryCode: 'JEY',
  },
  {
    code: 'JM',
    label: 'Jamaica',
    phone: '+1-876',
    countryCode: 'JAM',
  },
  {
    code: 'JO',
    label: 'Jordan',
    phone: '+962',
    countryCode: 'JOR',
  },
  {
    code: 'KE',
    label: 'Kenya',
    phone: '+254',
    countryCode: 'KEN',
  },
  {
    code: 'KG',
    label: 'Kyrgyzstan',
    phone: '+996',
    countryCode: 'KGZ',
  },
  {
    code: 'KH',
    label: 'Cambodia',
    phone: '+855',
    countryCode: 'KHM',
  },
  {
    code: 'KI',
    label: 'Kiribati',
    phone: '+686',
    countryCode: 'KIR',
  },
  {
    code: 'KM',
    label: 'Comoros',
    phone: '+269',
    countryCode: 'COM',
  },
  {
    code: 'KN',
    label: 'Saint Kitts and Nevis',
    phone: '+1-869',
    countryCode: 'KNA',
  },
  {
    code: 'KR',
    label: 'Korea, Republic of',
    phone: '+82',
    countryCode: 'KOR',
  },
  {
    code: 'KW',
    label: 'Kuwait',
    phone: '+965',
    countryCode: 'KWT',
  },
  {
    code: 'KY',
    label: 'Cayman Islands',
    phone: '+1-345',
    countryCode: 'CYM',
  },
  {
    code: 'KZ',
    label: 'Kazakhstan',
    phone: '+7',
    countryCode: 'KAZ',
  },
  {
    code: 'LA',
    label: "Lao People's Democratic Republic",
    phone: '+856',
    countryCode: 'LAO',
  },
  {
    code: 'LC',
    label: 'Saint Lucia',
    phone: '+1-758',
    countryCode: 'LCA',
  },
  {
    code: 'LI',
    label: 'Liechtenstein',
    phone: '+423',
    countryCode: 'LIE',
  },
  {
    code: 'LK',
    label: 'Sri Lanka',
    phone: '+94',
    countryCode: 'LKA',
  },

  {
    code: 'LS',
    label: 'Lesotho',
    phone: '+266',
    countryCode: 'LSO',
  },
  {
    code: 'LT',
    label: 'Lithuania',
    phone: '+370',
    countryCode: 'LTU',
  },
  {
    code: 'LU',
    label: 'Luxembourg',
    phone: '+352',
    countryCode: 'LUX',
  },
  {
    code: 'LV',
    label: 'Latvia',
    phone: '+371',
    countryCode: 'LVA',
  },
  {
    code: 'MA',
    label: 'Morocco',
    phone: '+212',
    countryCode: 'MAR',
  },
  {
    code: 'MC',
    label: 'Monaco',
    phone: '+377',
    countryCode: 'MCO',
  },
  {
    code: 'MD',
    label: 'Moldova, Republic of',
    phone: '+373',
    countryCode: 'MDA',
  },
  {
    code: 'ME',
    label: 'Montenegro',
    phone: '+382',
    countryCode: 'MNE',
  },
  {
    code: 'MF',
    label: 'Saint Martin (French part)',
    phone: '+590',
    countryCode: 'MAF',
  },
  {
    code: 'MG',
    label: 'Madagascar',
    phone: '+261',
    countryCode: 'MDG',
  },
  {
    code: 'MH',
    label: 'Marshall Islands',
    phone: '+692',
    countryCode: 'MHL',
  },
  {
    code: 'MK',
    label: 'Macedonia, the Former Yugoslav Republic of',
    phone: '+389',
    countryCode: 'MKD',
  },
  {
    code: 'MN',
    label: 'Mongolia',
    phone: '+976',
    countryCode: 'MNG',
  },
  {
    code: 'MO',
    label: 'Macao',
    phone: '+853',
    countryCode: 'MAC',
  },
  {
    code: 'MP',
    label: 'Northern Mariana Islands',
    phone: '+1-670',
    countryCode: 'MNP',
  },
  {
    code: 'MQ',
    label: 'Martinique',
    phone: '+596',
    countryCode: 'MTQ',
  },
  {
    code: 'MR',
    label: 'Mauritania',
    phone: '+222',
    countryCode: 'MRT',
  },
  {
    code: 'MS',
    label: 'Montserrat',
    phone: '+1-664',
    countryCode: 'MSR',
  },
  {
    code: 'MT',
    label: 'Malta',
    phone: '+356',
    countryCode: 'MLT',
  },
  {
    code: 'MU',
    label: 'Mauritius',
    phone: '+230',
    countryCode: 'MUS',
  },
  {
    code: 'MV',
    label: 'Maldives',
    phone: '+960',
    countryCode: 'MDV',
  },
  {
    code: 'MW',
    label: 'Malawi',
    phone: '+265',
    countryCode: 'MWI',
  },
  {
    code: 'MX',
    label: 'Mexico',
    phone: '+52',
    countryCode: 'MEX',
  },
  {
    code: 'MY',
    label: 'Malaysia',
    phone: '+60',
    countryCode: 'MYS',
  },
  {
    code: 'MZ',
    label: 'Mozambique',
    phone: '+258',
    countryCode: 'MOZ',
  },
  {
    code: 'NA',
    label: 'Namibia',
    phone: '+264',
    countryCode: 'NAM',
  },
  {
    code: 'NC',
    label: 'New Caledonia',
    phone: '+687',
    countryCode: 'NCL',
  },
  {
    code: 'NE',
    label: 'Niger',
    phone: '+227',
    countryCode: 'NER',
  },
  {
    code: 'NF',
    label: 'Norfolk Island',
    phone: '+672',
    countryCode: 'NFK',
  },
  {
    code: 'NG',
    label: 'Nigeria',
    phone: '+234',
    countryCode: 'NGA',
  },
  {
    code: 'NL',
    label: 'Netherlands',
    phone: '+31',
    countryCode: 'NLD',
  },
  {
    code: 'NO',
    label: 'Norway',
    phone: '+47',
    countryCode: 'NOR',
  },
  {
    code: 'NP',
    label: 'Nepal',
    phone: '+977',
    countryCode: 'NPL',
  },
  {
    code: 'NR',
    label: 'Nauru',
    phone: '+674',
    countryCode: 'NRU',
  },
  {
    code: 'NU',
    label: 'Niue',
    phone: '+683',
    countryCode: 'NIU',
  },
  {
    code: 'NZ',
    label: 'New Zealand',
    phone: '+64',
    countryCode: 'NZL',
  },
  {
    code: 'OM',
    label: 'Oman',
    phone: '+968',
    countryCode: 'OMN',
  },
  {
    code: 'PA',
    label: 'Panama',
    phone: '+507',
    countryCode: 'PAN',
  },
  {
    code: 'PE',
    label: 'Peru',
    phone: '+51',
    countryCode: 'PER',
  },
  {
    code: 'PF',
    label: 'French Polynesia',
    phone: '+689',
    countryCode: 'PYF',
  },
  {
    code: 'PG',
    label: 'Papua New Guinea',
    phone: '+675',
    countryCode: 'PNG',
  },
  {
    code: 'PH',
    label: 'Philippines',
    phone: '+63',
    countryCode: 'PHL',
  },
  {
    code: 'PK',
    label: 'Pakistan',
    phone: '+92',
    countryCode: 'PAK',
  },
  {
    code: 'PL',
    label: 'Poland',
    phone: '+48',
    countryCode: 'POL',
  },
  {
    code: 'PM',
    label: 'Saint Pierre and Miquelon',
    phone: '+508',
    countryCode: 'SPM',
  },
  {
    code: 'PN',
    label: 'Pitcairn',
    phone: '+870',
    countryCode: 'PCN',
  },
  {
    code: 'PR',
    label: 'Puerto Rico',
    phone: '+1',
    countryCode: 'PRI',
  },
  {
    code: 'PS',
    label: 'Palestine, State of',
    phone: '+970',
    countryCode: 'PSE',
  },
  {
    code: 'PT',
    label: 'Portugal',
    phone: '+351',
    countryCode: 'PRT',
  },
  {
    code: 'PW',
    label: 'Palau',
    phone: '+680',
    countryCode: 'PLW',
  },
  {
    code: 'PY',
    label: 'Paraguay',
    phone: '+595',
    countryCode: 'PRY',
  },
  {
    code: 'QA',
    label: 'Qatar',
    phone: '+974',
    countryCode: 'QAT',
  },
  {
    code: 'RE',
    label: 'Reunion',
    phone: '+262',
    countryCode: 'REU',
  },
  {
    code: 'RO',
    label: 'Romania',
    phone: '+40',
    countryCode: 'ROU',
  },
  {
    code: 'RS',
    label: 'Serbia',
    phone: '+381',
    countryCode: 'SRB',
  },
  {
    code: 'SA',
    label: 'Saudi Arabia',
    phone: '+966',
    countryCode: 'SAU',
  },
  {
    code: 'SB',
    label: 'Solomon Islands',
    phone: '+677',
    countryCode: 'SLB',
  },
  {
    code: 'SC',
    label: 'Seychelles',
    phone: '+248',
    countryCode: 'SYC',
  },
  {
    code: 'SE',
    label: 'Sweden',
    phone: '+46',
    countryCode: 'SWE',
  },
  {
    code: 'SH',
    label: 'Saint Helena',
    phone: '+290',
    countryCode: 'SHN',
  },
  {
    code: 'SI',
    label: 'Slovenia',
    phone: '+386',
    countryCode: 'SVN',
  },
  {
    code: 'SJ',
    label: 'Svalbard and Jan Mayen',
    phone: '+47',
    countryCode: 'SJM',
  },
  {
    code: 'SK',
    label: 'Slovakia',
    phone: '+421',
    countryCode: 'SVK',
  },
  {
    code: 'SM',
    label: 'San Marino',
    phone: '+378',
    countryCode: 'SMR',
  },
  {
    code: 'SN',
    label: 'Senegal',
    phone: '+221',
    countryCode: 'SEN',
  },
  {
    code: 'SR',
    label: 'Suriname',
    phone: '+597',
    countryCode: 'SUR',
  },
  {
    code: 'ST',
    label: 'Sao Tome and Principe',
    phone: '+239',
    countryCode: 'STP',
  },
  {
    code: 'SV',
    label: 'El Salvador',
    phone: '+503',
    countryCode: 'SLV',
  },
  {
    code: 'SX',
    label: 'Sint Maarten (Dutch part)',
    phone: '+1-721',
    countryCode: 'SXM',
  },
  {
    code: 'SZ',
    label: 'Swaziland',
    phone: '+268',
    countryCode: 'SWZ',
  },
  {
    code: 'TC',
    label: 'Turks and Caicos Islands',
    phone: '+1-649',
    countryCode: 'TCA',
  },
  {
    code: 'TD',
    label: 'Chad',
    phone: '+235',
    countryCode: 'TCD',
  },
  {
    code: 'TF',
    label: 'French Southern Territories',
    phone: '+262',
    countryCode: 'ATF',
  },
  {
    code: 'TG',
    label: 'Togo',
    phone: '+228',
    countryCode: 'TGO',
  },
  {
    code: 'TH',
    label: 'Thailand',
    phone: '+66',
    countryCode: 'THA',
  },
  {
    code: 'TJ',
    label: 'Tajikistan',
    phone: '+992',
    countryCode: 'TJK',
  },
  {
    code: 'TK',
    label: 'Tokelau',
    phone: '+690',
    countryCode: 'TKL',
  },
  {
    code: 'TL',
    label: 'Timor-Leste',
    phone: '+670',
    countryCode: 'TLS',
  },
  {
    code: 'TM',
    label: 'Turkmenistan',
    phone: '+993',
    countryCode: 'TKM',
  },
  {
    code: 'TN',
    label: 'Tunisia',
    phone: '+216',
    countryCode: 'TUN',
  },
  {
    code: 'TO',
    label: 'Tonga',
    phone: '+676',
    countryCode: 'TON',
  },
  {
    code: 'TR',
    label: 'Turkey',
    phone: '+90',
    countryCode: 'TUR',
  },
  {
    code: 'TT',
    label: 'Trinidad and Tobago',
    phone: '+1-868',
    countryCode: 'TTO',
  },
  {
    code: 'TV',
    label: 'Tuvalu',
    phone: '+688',
    countryCode: 'TUV',
  },
  {
    code: 'TW',
    label: 'Taiwan',
    phone: '+886',
    countryCode: 'TWN',
  },
  {
    code: 'TZ',
    label: 'United Republic of Tanzania',
    phone: '+255',
    countryCode: 'TZA',
  },
  {
    code: 'UG',
    label: 'Uganda',
    phone: '+256',
    countryCode: 'UGA',
  },
  {
    code: 'US',
    label: 'United States',
    phone: '+1',
    suggested: true,
    countryCode: 'USA',
  },
  {
    code: 'UY',
    label: 'Uruguay',
    phone: '+598',
    countryCode: 'URY',
  },
  {
    code: 'UZ',
    label: 'Uzbekistan',
    phone: '+998',
    countryCode: 'UZB',
  },
  {
    code: 'VA',
    label: 'Holy See (Vatican City State)',
    phone: '+379',
    countryCode: 'VAT',
  },
  {
    code: 'VC',
    label: 'Saint Vincent and the Grenadines',
    phone: '+1-784',
    countryCode: 'VCT',
  },
  {
    code: 'VE',
    label: 'Venezuela',
    phone: '+58',
    countryCode: 'VEN',
  },
  {
    code: 'VG',
    label: 'British Virgin Islands',
    phone: '+1-284',
    countryCode: 'VGB',
  },
  {
    code: 'VI',
    label: 'US Virgin Islands',
    phone: '+1-340',
    countryCode: 'VIR',
  },
  {
    code: 'VN',
    label: 'Vietnam',
    phone: '+84',
    countryCode: 'VNM',
  },
  {
    code: 'VU',
    label: 'Vanuatu',
    phone: '+678',
    countryCode: 'VUT',
  },
  {
    code: 'WF',
    label: 'Wallis and Futuna',
    phone: '+681',
    countryCode: 'WLF',
  },
  {
    code: 'WS',
    label: 'Samoa',
    phone: '+685',
    countryCode: 'WSM',
  },
  {
    code: 'XK',
    label: 'Kosovo',
    phone: '+383',
    countryCode: 'XKX',
  },
  {
    code: 'YT',
    label: 'Mayotte',
    phone: '+262',
    countryCode: 'MYT',
  },
  {
    code: 'ZA',
    label: 'South Africa',
    phone: '+27',
    countryCode: 'ZAF',
  },
  {
    code: 'ZM',
    label: 'Zambia',
    phone: '+260',
    countryCode: 'ZMB',
  },
];

export const PHYSICAL_CARD_COUNTRIES = {
  ARE: true,
  ATG: true,
  AIA: true,
  ALB: true,
  ARM: true,
  AGO: true,
  ATA: true,
  ARG: true,
  ASM: true,
  AUT: true,
  AUS: true,
  ABW: true,
  ALA: true,
  AZE: true,
  BRB: true,
  BGD: true,
  BEL: true,
  BFA: true,
  BGR: true,
  BHR: true,
  BEN: true,
  BLM: true,
  BMU: true,
  BRN: true,
  BOL: true,
  BRA: true,
  BHS: true,
  BTN: true,
  BVT: true,
  BWA: true,
  BLZ: true,
  CAN: true,
  CCK: true,
  COG: true,
  CHE: true,
  CIV: true,
  COK: true,
  CHL: true,
  CMR: true,
  COL: true,
  CRI: true,
  CPV: true,
  CUW: true,
  CXR: true,
  CYP: true,
  CZE: true,
  DEU: true,
  DJI: true,
  DNK: true,
  DMA: true,
  DOM: true,
  DZA: true,
  ECU: true,
  EST: true,
  EGY: true,
  ESH: true,
  ESP: true,
  ETH: true,
  FIN: true,
  FJI: true,
  FLK: true,
  FSM: true,
  FRO: true,
  FRA: true,
  GAB: true,
  GBR: true,
  GRD: true,
  GEO: true,
  GUF: true,
  GGY: true,
  GHA: true,
  GIB: true,
  GRL: true,
  GMB: true,
  GLP: true,
  GNQ: true,
  GRC: true,
  SGS: true,
  GTM: true,
  GUM: true,
  GNB: true,
  GUY: true,
  HKG: true,
  HMD: true,
  HND: true,
  HUN: true,
  IRL: true,
  ISR: true,
  IMN: true,
  IOT: true,
  ISL: true,
  ITA: true,
  JEY: true,
  JAM: true,
  JOR: true,
  KEN: true,
  KGZ: true,
  KHM: true,
  KIR: true,
  COM: true,
  KNA: true,
  KOR: true,
  KWT: true,
  CYM: true,
  KAZ: true,
  LAO: true,
  LCA: true,
  LIE: true,
  LKA: true,
  LSO: true,
  LTU: true,
  LUX: true,
  LVA: true,
  MAR: true,
  MCO: true,
  MDA: true,
  MAF: true,
  MDG: true,
  MHL: true,
  MNG: true,
  MAC: true,
  MNP: true,
  MTQ: true,
  MRT: true,
  MSR: true,
  MLT: true,
  MUS: true,
  MDV: true,
  MWI: true,
  MYS: true,
  MOZ: true,
  NAM: true,
  NCL: true,
  NER: true,
  NFK: true,
  NLD: true,
  NOR: true,
  NPL: true,
  NRU: true,
  NIU: true,
  NZL: true,
  OMN: true,
  PAN: true,
  PER: true,
  PYF: true,
  PNG: true,
  PHL: true,
  PAK: true,
  POL: true,
  SPM: true,
  PCN: true,
  PRI: true,
  PSE: true,
  PRT: true,
  PLW: true,
  PRY: true,
  QAT: true,
  REU: true,
  ROU: true,
  SRB: true,
  SLB: true,
  SYC: true,
  SWE: true,
  SHN: true,
  SJM: true,
  SVK: true,
  SMR: true,
  SEN: true,
  SUR: true,
  STP: true,
  SLV: true,
  SXM: true,
  SWZ: true,
  TCA: true,
  TCD: true,
  ATF: true,
  TGO: true,
  THA: true,
  TJK: true,
  TKL: true,
  TLS: true,
  TKM: true,
  TUN: true,
  TON: true,
  TTO: true,
  TUV: true,
  TZA: true,
  UGA: true,
  USA: true,
  URY: true,
  UZB: true,
  VAT: true,
  VCT: true,
  VEN: true,
  VGB: true,
  VIR: true,
  VUT: true,
  WLF: true,
  WSM: true,
  XKX: true,
  MYT: true,
  ZAF: true,
  ZMB: true,
};
